psia_python/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("", include("psia_python_app.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psia_python_app/urls.py
from django.urls import path
from .views import profile_list, profile, dashboard, imagepost

app_name = "psia_python_app"

urlpatterns = [
    # path('index/', index, name='home'),
    path("", dashboard, name="dashboard"),
    path('profile_list', profile_list, name='profile_list'),
    path('profile/<int:pk>', profile, name='profile'),
    path('imageposts/<int:imagepost_id>', imagepost, name='imagepost')
]

psia_python_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserPost(models.Model):
  user = models.ForeignKey(
    User, related_name='userposts', on_delete=models.DO_NOTHING
  )
  body = models.CharField(max_length=500)
  image = models.ImageField(blank = True, upload_to='images/')
  profile_image = models.ImageField(blank = True, upload_to='images/')
  created_at = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    return (
      f"{self.image} "
      f"{self.profile_image} "
      f"{self.user} "
      f"{self.created_at:%Y-%m-%d %H:%M}: "
      f"{self.body[:30]}..."
    )

class ImagePost(models.Model):
  title = models.CharField(max_length=50)
  # image = models.ImageField(upload_to='files/covers')
  
  def __str__(self):
    return self.title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return(
          f"{self.user.username} "
          )

        
    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
      if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()

psia_python_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import ImagePost, UserPost

class UserPostForm(forms.ModelForm):
      image = forms.ImageField(
        required=True,
      )
      body = forms.CharField(
      required=True,
      widget=forms.widgets.Textarea(
          attrs={
              "placeholder": "Post something...",
              "class": "textarea is-success is-medium",
          }
      ),
      label="",
  )

      class Meta:
        model = UserPost
        fields = ('body', )
        exclude = ("user", )

psia_python_app/views.py
from email.mime import image
from django.http import Http404
from django.shortcuts import render, redirect
from .forms import UserPostForm
from .models import UserPost, Profile, ImagePost

def dashboard(request):
  if request.method == "POST":
    form = UserPostForm(request.POST or None)
    if form.is_valid():
      userpost = form.save(commit=False)
      userpost.user = request.user
      userpost.save()
      return redirect("psia_python_app:dashboard")

  followed_userposts = UserPost.objects.filter(
    user__profile__in=request.user.profile.follows.all()
  ).order_by("-created_at")
  form = UserPostForm()
  return render(
    request, 
    "psia_python_app/dashboard.html", 
    {'form': form, 'userposts': followed_userposts}
  )

def profile_list(request):
  profiles = Profile.objects.exclude(user=request.user)
  return render(
    request, 
    'psia_python_app/profile_list.html', 
    {'profiles': profiles}
  )

def profile(request, pk):
  if not hasattr(request.user, 'profile'):
      missing_profile = Profile(user=request.user)
      missing_profile.save()

  profile = Profile.objects.get(pk=pk)
  if request.method == "POST":
    current_user_profile = request.user.profile
    data = request.POST
    action = data.get("follow")
    if action == "follow":
        current_user_profile.follows.add(profile)
    elif action == "unfollow":
        current_user_profile.follows.remove(profile)
    current_user_profile.save()
  return render(request, "psia_python_app/profile.html", {"profile": profile})

def imagepost(request, imagepost_id):
  imagepost = ImagePost.objects.get(pk=imagepost_id)
  if imagepost is not None:
    return render(request, 'imageposts/image.html', {'imagepost': imagepost})
  else:
    raise Http404("image not found.")

# def index(request):
#   return render(request, 'psia_python_app/index.html', Context)

psia_python_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <!-- <link rel="stylesheet" href="psia_python_app/static/css/main.css"> -->
    <title>PSIA</title>
</head>
<body class="has-background-light">
<a href="{% url 'psia_python_app:dashboard' %} ">
<section class="hero is-small is-dark mb-4">
    <div class="hero-body">
        {% load static %}
        <img src="media/images/Banner_Logo_Long_2.png" alt="PSIA logo banner">
        <p class="subtitle is-size-6">
            What is happening in your community?
        </p>
    </div>
</section>
</a>
<div class="container has-background-light">
    <div class="columns has-background-light">

        {% block content %}

        {% endblock content %}

    </div>
</div>
</body>
</html>

psia_python_app/templates/psia_python_app/dashboard.html
{% extends 'base.html' %}

{% block content %}
{%load static%}
<div class="column">
    {% for userpost in userposts %}
        <div class="box is-size-4 has-text-weight-medium">
            <figure class="image is-square">
            <img src="
            {{userpost.image.url}}">
            <br />
            </figure>
            {{userpost.body}}
            <br/>
            <span class="is-size-7 has-text-grey-light">
                {{ userpost.created_at }} by {{ userpost.user.username }}
            </span>
        </div>
    {% endfor %}
</div>


<div class="column is-one-third">
    <div class="block">
    <a href="{% url 'psia_python_app:profile_list' %} ">
        <button class="button is-dark is-outlined is-fullwidth">
            All Profiles
        </button>
    </a>
</div>
<div class="block">
    <a href="{% url 'psia_python_app:profile' request.user.profile.id %} ">
        <button class="button is-success is-light is-outlined is-fullwidth">
            My Profile
        </button>
    </a>
    <div class="block">
        <div class="block">
            <h2 class="title is-2">New Image</p>
        </div>
        <div class="block">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Post
                </button>
            </form>
            {% if img_obj %}
                <img src="{{ userpost.image.url }}" alt="connect" style="max-height:100px">
            {% endif %}
        </div>
    </div>

{% endblock content %}

psia_python_app/templates/psia_python_app/index.html
<!-- {% extends 'base.html' %}

{% block content %}

Hello, {{ user.username|default:'Guest' }}!

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</div>

{% endblock %} -->

psia_python_app/templates/psia_python_app/profile.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<div class="column">

        <div class="block">
        <h1 class="title is-1">
            {{profile.user.username}}'s Upcoming Events
        </h1>
        <form method="post">
            {% csrf_token %}
            <div class="buttons has-addons">
            {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">
                Unfollow
                </button>
            {% else %}
                <button class="button is-success" name="follow" value="follow">
                Follow
                </button>
                <button class="button is-danger is-static">Unfollow</button>
            {% endif %}
            </div>
        </form>
    </div>

    <div class="column">
        {% for userpost in profile.user.userposts.all %}
            <div class="box is-size-4 has-text-weight-medium">
                <p class="title is-4 is-pulled-right">{{profile.user.username}}</p>
                <figure class="image is-96x96">
                    <img class="is-rounded" src="
                    {{userpost.profile_image.url}}" width="100" height="100" float="media-left">
                </figure>
                <br/>
                {{ userpost.body }}
                <br/>
                <figure class="imgage is-square">
                    <img src="
                    {{userpost.image.url}}" width="500" height="500">
                </figure>
                <br/>
                <span class="is-small has-text-grey-light">
                    ({{ userpost.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>

<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'psia_python_app:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'psia_python_app:profile' following.id %} ">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'psia_python_app:profile' follower.id %} ">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock content %}

psia_python_app/templates/psia_python_app/profile_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'psia_python_app:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <div class="content">
                  {% for userpost in profile.user.userposts.all %}
                        <figure class="image is-96x96">
                          <img class="is-rounded" src="
                          {{userpost.profile_image.url}}" width="100" height="100" float="media-left">
                        </figure>
                  {% endfor %}
                </div>
              </div>
              <div class="media-content">
                <p class="title is-2">
                  {{profile.user.profile_image.url}}
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-size-4">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

psia_python_app/templates/psia_python_app/register.html
<!-- {% extends 'base.html' %}

{% block content %}
<h2>Register</h2>

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
</form>

<a href="{% url 'login' %}">Back to login</a>
{% endblock %} -->